server:
  address: 127.0.0.1

vaadin:
  servlet:
    # urlMapping: /app/*
    params:
      productionMode: true
      widgetset: 'app'

spring:
  groovy:
    template:
      check-template-location: false

---

spring:
    profiles: dev

vaadin:
  servlet:
    params:
      productionMode: false
      widgetset: 'app'
